---

# Unused redundent packages and related users are removed in a pre_task
# Necessary packages, users, groups are added in a pre_task

- name: Is MailScanner installed ?
  shell: dpkg -l mailscanner
  register: has_mailscanner
  changed_when: has_mailscanner.rc != 0
  failed_when: false

- name: Download MailScanner
  when: has_mailscanner.rc != 0
  shell: "wget -O- https://s3.amazonaws.com/msv5/release/MailScanner-5.0.3-7.deb.tar.gz | tar zx"
  args:
    chdir: /tmp
    creates: MailScanner-5.0.3-7

# MailScanner is not in repos; it uses some artisanal debconf with its ./install.sh
- name: MailScanner initial setup
  when: has_mailscanner.rc != 0
  shell: "/bin/echo -e '\nN\nn\ny\nn\nNone\npostmaster@slash16.local' | ./install.sh"
  args:
    chdir: /tmp/MailScanner-5.0.3-7

- name: Ensure config directory structure is correct
  file: >
    path={{ item.path }}
    state=directory
    owner={{ item.owner }}
    group={{ item.group }} 
    mode={{ item.mode }}
  with_items: mail_config_dirs

- name: Dump config files
  copy: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items: mail_config_files
  notify:
    - Compile postfix hashmaps
    - Enable and Restart mail daemons

- name: Ensure important symlinks are correct
  file: path={{ item.link }} state=link src={{ item.src }} force=yes
  with_items: mail_symlinks

- name: Ensure key mail spool dirs are correct
  file: >
    path={{ item.path }}
    state=directory
    owner={{ item.owner }}
    group={{ item.group }} 
    mode={{ item.mode }}
  with_items: mail_spool_dirs

...
