---
- name: restart prosody
  action: service name=prosody state=restarted

- name: restart saslauthd
  action: service name=saslauthd state=restarted

- name: reload systemd
  command: systemctl daemon-reload

- name: Restart PostgreSQL
  delegate_to: 192.168.154.8
  service: name=postgresql state=restarted
  sudo_user: root
  sudo: yes

...
