---
- name: django_user can create database
  postgresql_user: name=django_user role_attr_flags=CREATEDB

- name: Create new user for replication role
  postgresql_user: name={{rep_user}} password={{rep_pswd}}
                   role_attr_flags=REPLICATION

- name: Add config for replication user
  lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
              line="host    replication     {{rep_user}}      192.168.154.7/32            md5"
  notify: Restart PostgreSQL

- name: accept connections from web1 for main db
  lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
              line="host    django_db     django_user      192.168.154.4/32            md5"
  notify: Restart PostgreSQL

- name: accept connections from web2 for main db
  lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
              line="host    django_db     django_user      192.168.154.5/32            md5"
  notify: Restart PostgreSQL

- name: accept connections from web1 for test db
  lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
              line="host    test_django_db     django_user      192.168.154.4/32            md5"
  notify: Restart PostgreSQL

- name: accept connections from web2 for test db
  lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
              line="host    test_django_db     django_user      192.168.154.5/32            md5"
  notify: Restart PostgreSQL

- name: Creates directory for archive configuration
  file: path=/var/lib/postgresql/9.4/main/archive
        state=directory
        owner=postgres group=postgres
  sudo_user: root
  sudo: yes

- name: Enable archive mode in PostgreSQL configuration
  lineinfile: dest=/etc/postgresql/9.4/main/postgresql.conf
              regexp="^archive_mode ="
              line="archive_mode = on"
  notify: Restart PostgreSQL

- name: Set archive command in PostgreSQL configuration
  lineinfile: dest=/etc/postgresql/9.4/main/postgresql.conf
              regexp="^archive_command ="
              line="archive_command = 'test ! -f /var/lib/postgresql/9.4/main/archive/%f && cp %p /var/lib/postgresql/9.4/main/archive/%f'"
  notify: Restart PostgreSQL

- name: Enable hot stanby in PostgreSQL configuration
  lineinfile: dest=/etc/postgresql/9.4/main/postgresql.conf
              regexp="^wal_level ="
              line="wal_level = hot_standby"
  notify: Restart PostgreSQL

- name: Set max WAL senders in PostgreSQL configuration
  lineinfile: dest=/etc/postgresql/9.4/main/postgresql.conf
              regexp="^max_wal_senders ="
              line="max_wal_senders = 3"
  notify: Restart PostgreSQL
...
