---
- name: backports repo
  apt_repository: >
    repo='deb http://ftp.debian.org/debian jessie-backports main'
    state=present

- name: Install backports libpq-dev
  apt: name=libpq-dev state=latest default-release=jessie-backports

- name: Install needed apt packages
  apt: name="{{item}}" state=present
  with_items:
    - python3-pip
    - python3-venv
    - python3-dev
    - virtualenv
    - nginx
    - gcc

- name: Install a wrapper for virtualenv (ugly workaround)
  copy: src=virtualenv3
        dest=/usr/local/bin/virtualenv3
        mode=0555

# Django user #
###############
- name: Create django group
  group: name=django state=present

- name: Create django user
  user: name=django group=django shell=/bin/false

# Django & nginx conf #
#######################
- name: Setup Django service config
  template: src=django.service
            dest=/etc/systemd/system/django.service
  notify:
    - reload systemd 

- name: /var/www for django group
  file: path=/var/www group=django mode=0775

- name: Setup Django virtualhost
  template: src=nginx-django
            dest=/etc/nginx/sites-available/django
  notify: Restart nginx service

- name: Enable Django virtualhost
  file: src=/etc/nginx/sites-available/django 
        dest=/etc/nginx/sites-enabled/django 
        state=link
  notify: Restart nginx service

- name: Disable nginx default virtualhost
  file: path=/etc/nginx/sites-available/default 
        state=absent
  notify: Restart nginx service

- name: Setup server names bucket size in nginx.conf
  lineinfile: dest=/etc/nginx/nginx.conf
              insertafter='^http {$'
              line="server_names_hash_bucket_size 64;"
  notify: Restart nginx service

- name: Start and enable nginx service
  service: name=nginx state=started enabled=yes

# PostgreSQL #
##############

- name: Install PostgreSQL packages and pip
  apt: name={{item}} state=present
  with_items:
    - postgresql={{postgres_version}}
    - postgresql-contrib={{postgres_version}}
    - postgresql-server-dev-all
    - python-pip
    - python-dev

- name: Install the Python psycopg2 module
  pip: name=psycopg2 executable=/usr/bin/pip

- name: Create Django database
  postgresql_db: name=django_db template=template0 encoding=utf8
  sudo_user: postgres
  sudo: yes

- name: Create Django database user
  postgresql_user: name=django_user password=django_user
                   db=django_db priv=ALL role_attr_flags=CREATEDB
  sudo_user: postgres
  sudo: yes

- name: Start and enable postgresql service
  service: name=postgresql state=started enabled=yes

- name: Set db_read alias in /etc/hosts
  lineinfile: dest=/etc/hosts
              line="127.0.0.1  db_read"

- name: Set db_write alias in /etc/hosts
  lineinfile: dest=/etc/hosts
              line="127.0.0.1  db_write"
...
