---
- name: Rsyslog - Listen to remote logging
  template:
    src=rsyslog/rsyslog.d/30-log-server.conf.j2
    dest=/etc/rsyslog.d/30-log-server.conf
  notify: Restart rsyslog

- name: Rsyslog/Logrotate - logserver-specific rotation policy
  template:
    src=logrotate/logrotate.d/rsyslog-centralized
    dest=/etc/logrotate.d/rsyslog-centralized
...
