---
- name: Update tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Restart rsyslog
  service: name=rsyslog state=restarted

- name: Restart Zabbix agent
  service: name=zabbix-agent state=restarted

- name: Restart exim4
  service: name=exim4 state=restarted
...
