---
- name: Install necessary packages
  apt: name="{{item}}" state=present
  with_items:
    - vsftpd

# Started ?
- name: pure-ftpd is started
  service: name=pure-ftpd-ldap state=started enabled=true
...
