---

- name: Ansible packages
  sudo: yes
  sudo_user: root
  apt: state=present name=ansible

- name: Backup agent tree
  copy:
    src: backup-agent
    dest: /home/ansible/

#- name: Setup cronjob for the backup agent

...
