---

# Create backup-agent@srv3
# Generate an id key
# Run a boostrap playbook to push its key to target hosts

- name: Ansible packages
  sudo: yes
  sudo_user: root
  apt: state=present name=ansible

- name: Add user backup-agent
  sudo: yes
  sudo_user: root
  user:
    name: backup-agent
 
- name: Generate backup-agent@srv3 SSH id (private dir)
  changed_when: true
  notify: Remove backup agent local_id_dir
  local_action: >
    file
    state=directory
    path={{backup_agent_local_id_dir.path}}
    mode={{backup_agent_local_id_dir.mode}}

- name: Generate backup-agent@srv3 SSH id (key pair)
  changed_when: true
  register: pub_key
  local_action: >
    shell
    echo y |
    ssh-keygen -C {{pubkey_comment}} -N '' -f {{backup_agent_ssh_id}} >/dev/null
    &&
    tail -n1 {{backup_agent_ssh_id}}.pub

- name: backup-agent@srv3 operation dirtree
  sudo: yes
  sudo_user: backup-agent
  with_items: backup_agent_dirtree
  file: >
    state=directory
    path={{item.dir}}
    mode={{item.mode}}
    owner=backup-agent
    group=backup-agent

- name: backup-agent@srv3 keys and operational files
  with_items: backup_agent_files
  sudo: yes
  sudo_user: backup-agent
  copy: >
    src={{item.src}}
    dest={{item.dest}}
    owner=backup-agent
    group=backup-agent
    mode={{item.mode}}
 
- name: Purge previous backup-agent public id
  with_items: authorized_keys_targets
  delegate_to: "{{item.initial_host}}"
  sudo: yes
  sudo_user: "{{item.rem_user}}"
  lineinfile:
    dest: "/home/{{item.rem_user}}/.ssh/authorized_keys"
    state: absent
    regexp: "^.*{{pubkey_comment}}$"

- name: Authorize backup-agent public id
  with_items: authorized_keys_targets
  delegate_to: "{{item.initial_host}}"
  sudo: yes
  authorized_key:
    user: "{{item.rem_user}}"
    state: present
    key: "{{pub_key.stdout}}"

- name: Setup cron for the backup agent
  sudo: yes
  sudo_user: backup-agent
  cron: >
    user=backup-agent
    hour=5
    minute=30
    job=/home/backup-agent/cronjobs/bin/agent-fetch.sh
    state=present
    name="Backup agent daily sync"

...
