

- name: Install mail service and dependencies packages
  apt: name={{ item }} state=present
  with_items: mail_packages
  notify: Stop and Disable mail daemons

- name: Setup service groups
  group: name={{ item.name }} gid={{ item.gid }} state=present
  with_items: mail_system_groups

- name: Setup service users and groups
  user: >
    name={{ item.name }}
    gid={{ item.uid }}
    group={{ item.group }}
    groups={{ item.groups }}
    home={{ item.home }}
    createhome=no
    shell={{ item.shell }}
  with_items: mail_system_users
