---

- name: Install mail service and dependencies packages
  apt: name={{ item }} state=present
  with_items: mail_packages
  notify:
    - Stop and Disable mail daemons
    - Nuke default config

- name: Setup service groups
  group: name={{ item.name }} state=present system={{ item.is_system }}
  with_items: mail_system_groups

- name: Setup service users and user groups
  user: >
    name={{ item.name }}
    group={{ item.group }}
    groups={{ item.groups }}
    home={{ item.homedir }}
    createhome=no
    shell={{ item.shell }}
  with_items: mail_system_users

...
