

- name: Purge exim4
  apt: name={{ item }} state=absent purge=yes
  with_items: mail_redundent_packages
  notify: Kill anything using mail ports

- name: Remove exim user
  user: name=Debian-exim state=absent

- name: Remove exim group
  group: name=Debian-exim state=absent

