---

- name: Setup mail
  hosts: mail
  remote_user: root
  tags: mail
  roles: [mail]
  pre_tasks:
    - include: roles/mail/pre_tasks/main.yml
    - include: roles/mail/pre_tasks/purge-redundent.yml
    - meta: flush_handlers
    - include: roles/mail/pre_tasks/install-packages.yml
    - meta: flush_handlers
...
